version: "3.9"
services:
  api:
    image: webdevops/php-nginx-dev:8.1
    ports:
      - "8089:80"
    volumes:
      - '/api:/api'
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      XDEBUG_CLIENT_HOST: "host.docker.internal"
      XDEBUG_DISCOVER_CLIENT_HOST: "false"
      XDEBUG_MODE: "debug,coverage"
      XDEBUG_IDE_KEY: "PHPSTORM"
      XDEBUG_CLIENT_PORT: "9003"
      COMPOSER_HOME: "/app/.composer"
      PHP_DATE_TIMEZONE: "Europe/Madrid"
      PHP_IDE_CONFIG: "serverName=_"
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "4173:4173"
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 8000"
  pgsql:
    image: postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: '${DB_DATABASE:-example}'
      POSTGRES_USER: '${DB_USERNAME:-balibrea}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_HOST: '${DB_HOST:-host.docker.internal}'